on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ inputs.image_name }}"
          push: true
          tags: ghcr.io/ooedo-samurai/${{ inputs.image_name }}:latest
